FROM nvidia/cuda:12.1.0-base-ubuntu20.04

RUN apt-get update && apt-get install -y git python3-pip wget && apt-get clean

RUN pip install --upgrade pip
RUN pip install vllm[openai]==0.9.2

CMD ["python3", "-m", "vllm.entrypoints.openai.api_server", "--model", "nanonets/Nanonets-OCR-s"]
